FROM {{ namespace }}/{{ image_prefix }}nova-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block nova_conductor_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

        {% set nova_conductor_packages = [
            'openstack-nova-conductor'
        ] %}

    {% elif base_distro in ['ubuntu'] %}

        {% set nova_conductor_packages = [
            'nova-conductor',
            'librados2=0.94.*',
            'librbd1=0.94.*',
            'python-rados=0.94.*',
            'python-cephfs=0.94.*',
            'python-rbd=0.94.*',
            'ceph-common=0.94.*',
            '--allow-unauthenticated'
        ] %}

    {% endif %}

{{ macros.install_packages(nova_conductor_packages | customizable("packages")) }}

{% endif %}

{% block nova_conductor_footer %}{% endblock %}
{% block footer %}{% endblock %}
{{ include_footer }}

USER nova
